import z from 'zod'

const invoiceMakerSchemas = {
  invoices: {
    schema: z.object({
      invoice_number: z.string(),
      bill_to: z.string(),
      date: z.string(),
      due_date: z.string(),
      payment_terms: z.string(),
      po_number: z.string(),
      status: z.enum(['draft', 'sent', 'paid', 'overdue', 'cancelled', '']),
      shipping_address: z.string(),
      tax_type: z.enum(['rate', 'fixed', '']),
      tax_amount: z.number(),
      discount_type: z.enum(['rate', 'fixed', '']),
      discount_amount: z.number(),
      shipping_amount: z.number(),
      amount_paid: z.number(),
      notes: z.string(),
      created: z.string(),
      updated: z.string()
    }),
    raw: {
      id: 'pbc_2028188723',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: 'invoice_maker__invoices',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text765886983',
          max: 0,
          min: 0,
          name: 'invoice_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_3022276037',
          hidden: false,
          id: 'relation1915922273',
          maxSelect: 1,
          minSelect: 0,
          name: 'bill_to',
          presentable: false,
          required: false,
          system: false,
          type: 'relation'
        },
        {
          hidden: false,
          id: 'date2862495610',
          max: '',
          min: '',
          name: 'date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          hidden: false,
          id: 'date3866337329',
          max: '',
          min: '',
          name: 'due_date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3756722627',
          max: 0,
          min: 0,
          name: 'payment_terms',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3987620549',
          max: 0,
          min: 0,
          name: 'po_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'select2063623452',
          maxSelect: 1,
          name: 'status',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['draft', 'sent', 'paid', 'overdue', 'cancelled']
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3943065925',
          max: 0,
          min: 0,
          name: 'shipping_address',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'select2421250257',
          maxSelect: 1,
          name: 'tax_type',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['rate', 'fixed']
        },
        {
          hidden: false,
          id: 'number3262847721',
          max: null,
          min: null,
          name: 'tax_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'select308040339',
          maxSelect: 1,
          name: 'discount_type',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['rate', 'fixed']
        },
        {
          hidden: false,
          id: 'number3772865661',
          max: null,
          min: null,
          name: 'discount_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'number2784736525',
          max: null,
          min: null,
          name: 'shipping_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'number2484990468',
          max: null,
          min: null,
          name: 'amount_paid',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text18589324',
          max: 0,
          min: 0,
          name: 'notes',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate'
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate'
        }
      ],
      indexes: [],
      system: false
    }
  },
  items: {
    schema: z.object({
      invoice: z.string(),
      description: z.string(),
      quantity: z.number(),
      rate: z.number(),
      order: z.number()
    }),
    raw: {
      id: 'pbc_812090032',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: 'invoice_maker__items',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_2028188723',
          hidden: false,
          id: 'relation2422544196',
          maxSelect: 1,
          minSelect: 0,
          name: 'invoice',
          presentable: false,
          required: false,
          system: false,
          type: 'relation'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1843675174',
          max: 0,
          min: 0,
          name: 'description',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'number2683508278',
          max: null,
          min: null,
          name: 'quantity',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'number3756801849',
          max: null,
          min: null,
          name: 'rate',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'number4113142680',
          max: null,
          min: null,
          name: 'order',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        }
      ],
      indexes: [],
      system: false
    }
  },
  clients: {
    schema: z.object({
      name: z.string(),
      address: z.string(),
      email: z.string(),
      phone: z.string(),
      created: z.string(),
      updated: z.string()
    }),
    raw: {
      id: 'pbc_3022276037',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: 'invoice_maker__clients',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1579384326',
          max: 0,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text223244161',
          max: 0,
          min: 0,
          name: 'address',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3885137012',
          max: 0,
          min: 0,
          name: 'email',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1146066909',
          max: 0,
          min: 0,
          name: 'phone',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate'
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate'
        }
      ],
      indexes: [],
      system: false
    }
  },
  settings: {
    schema: z.object({
      company_name: z.string(),
      company_additional_info: z.string(),
      default_logo: z.string(),
      default_payment_terms: z.string(),
      default_notes: z.string(),
      default_tax_rate: z.number(),
      bank_name: z.string(),
      bank_account: z.string(),
      currency: z.string(),
      currency_symbol: z.string(),
      invoice_prefix: z.string(),
      next_invoice_number: z.number(),
      created: z.string(),
      updated: z.string()
    }),
    raw: {
      id: 'pbc_4152965987',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: 'invoice_maker__settings',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text491676904',
          max: 0,
          min: 0,
          name: 'company_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1825036814',
          max: 0,
          min: 0,
          name: 'company_additional_info',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'file2709496085',
          maxSelect: 1,
          maxSize: 0,
          mimeTypes: [
            'image/jpeg',
            'image/png',
            'image/svg+xml',
            'image/gif',
            'image/webp'
          ],
          name: 'default_logo',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: [],
          type: 'file'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3922367952',
          max: 0,
          min: 0,
          name: 'default_payment_terms',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3896373890',
          max: 0,
          min: 0,
          name: 'default_notes',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'number3307667599',
          max: null,
          min: null,
          name: 'default_tax_rate',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text4098043016',
          max: 0,
          min: 0,
          name: 'bank_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1403141642',
          max: 0,
          min: 0,
          name: 'bank_account',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1767278655',
          max: 0,
          min: 0,
          name: 'currency',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1213075606',
          max: 0,
          min: 0,
          name: 'currency_symbol',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text679943133',
          max: 0,
          min: 0,
          name: 'invoice_prefix',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'number2302103150',
          max: null,
          min: null,
          name: 'next_invoice_number',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate'
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate'
        }
      ],
      indexes: [],
      system: false
    }
  },
  invoices_aggregated: {
    schema: z.object({
      invoice_number: z.string(),
      bill_to: z.string(),
      date: z.string(),
      due_date: z.string(),
      payment_terms: z.string(),
      po_number: z.string(),
      status: z.enum(['draft', 'sent', 'paid', 'overdue', 'cancelled', '']),
      shipping_address: z.string(),
      tax_type: z.enum(['rate', 'fixed', '']),
      tax_amount: z.number(),
      discount_type: z.enum(['rate', 'fixed', '']),
      discount_amount: z.number(),
      shipping_amount: z.number(),
      amount_paid: z.number(),
      notes: z.string(),
      created: z.string(),
      updated: z.string(),
      subtotal: z.any(),
      item_count: z.any(),
      calculated_tax: z.any(),
      calculated_discount: z.any(),
      calculated_shipping: z.any()
    }),
    raw: {
      id: 'pbc_2368357959',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: null,
      updateRule: null,
      deleteRule: null,
      name: 'invoice_maker__invoices_aggregated',
      type: 'view',
      fields: [
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3208210256',
          max: 0,
          min: 0,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_iST8',
          max: 0,
          min: 0,
          name: 'invoice_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_3022276037',
          hidden: false,
          id: '_clone_VS3C',
          maxSelect: 1,
          minSelect: 0,
          name: 'bill_to',
          presentable: false,
          required: false,
          system: false,
          type: 'relation'
        },
        {
          hidden: false,
          id: '_clone_JzRE',
          max: '',
          min: '',
          name: 'date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          hidden: false,
          id: '_clone_pLCQ',
          max: '',
          min: '',
          name: 'due_date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_wfPo',
          max: 0,
          min: 0,
          name: 'payment_terms',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_WNRn',
          max: 0,
          min: 0,
          name: 'po_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: '_clone_hkJI',
          maxSelect: 1,
          name: 'status',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['draft', 'sent', 'paid', 'overdue', 'cancelled']
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_oemq',
          max: 0,
          min: 0,
          name: 'shipping_address',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: '_clone_9n1o',
          maxSelect: 1,
          name: 'tax_type',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['rate', 'fixed']
        },
        {
          hidden: false,
          id: '_clone_MRKE',
          max: null,
          min: null,
          name: 'tax_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: '_clone_bDUQ',
          maxSelect: 1,
          name: 'discount_type',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['rate', 'fixed']
        },
        {
          hidden: false,
          id: '_clone_Ug0M',
          max: null,
          min: null,
          name: 'discount_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: '_clone_qCud',
          max: null,
          min: null,
          name: 'shipping_amount',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          hidden: false,
          id: '_clone_e8GT',
          max: null,
          min: null,
          name: 'amount_paid',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_miVD',
          max: 0,
          min: 0,
          name: 'notes',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: '_clone_NYeL',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate'
        },
        {
          hidden: false,
          id: '_clone_6cwd',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate'
        },
        {
          hidden: false,
          id: 'json3097235076',
          maxSize: 1,
          name: 'subtotal',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          hidden: false,
          id: 'json2944294834',
          maxSize: 1,
          name: 'item_count',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          hidden: false,
          id: 'json1853381339',
          maxSize: 1,
          name: 'calculated_tax',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          hidden: false,
          id: 'json1531123106',
          maxSize: 1,
          name: 'calculated_discount',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          hidden: false,
          id: 'json2545923720',
          maxSize: 1,
          name: 'calculated_shipping',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        }
      ],
      indexes: [],
      system: false,
      viewQuery:
        "SELECT \n    i.id,\n    i.invoice_number,\n    i.bill_to,\n    i.date,\n    i.due_date,\n    i.payment_terms,\n    i.po_number,\n    i.status,\n    i.shipping_address,\n    i.tax_type,\n    i.tax_amount,\n    i.discount_type,\n    i.discount_amount,\n    i.shipping_amount,\n    i.amount_paid,\n    i.notes,\n    i.created,\n    i.updated,\n    COALESCE(agg.subtotal, 0) AS subtotal,\n    COALESCE(agg.item_count, 0) AS item_count,\n    IIF(i.tax_type = 'rate', COALESCE(agg.subtotal, 0) * i.tax_amount / 100, IIF(i.tax_type = 'fixed', i.tax_amount, 0)) AS calculated_tax,\n    IIF(i.discount_type = 'rate', COALESCE(agg.subtotal, 0) * i.discount_amount / 100, IIF(i.discount_type = 'fixed', i.discount_amount, 0)) AS calculated_discount,\n    COALESCE(i.shipping_amount, 0) AS calculated_shipping\nFROM invoice_maker__invoices i\nLEFT JOIN (\n    SELECT \n        invoice,\n        SUM(quantity * rate) AS subtotal,\n        COUNT(*) AS item_count\n    FROM invoice_maker__items\n    GROUP BY invoice\n) agg ON agg.invoice = i.id;"
    }
  }
}

export default invoiceMakerSchemas
